language: php

matrix:
    include:
        - php: 7.1
        - php: 7.2
    fast_finish: true

sudo: false

git:
    depth: 1

cache:
    - $HOME/.composer/cache/files
    - .phpunit

before_install:
    - export SYMFONY_PHPUNIT_DIR="$(pwd)/.phpunit"
    - echo memory_limit = -1 >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - phpenv config-rm xdebug.ini

install:
    - composer install

script:
    - ./vendor/bin/simple-phpunit
