name: Lint and analyse files

on: 
  push:
  pull_request:
    branches:
      # Branches from forks have the form 'user:branch-name' so we only run
      # this job on pull_request events for branches that look like fork
      # branches. Without this we would end up running this job twice for non
      # forked PRs, once for the push and then once for opening the PR.
      # Source: https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/10
    - '**:**'

jobs:
    lint-php:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use php 7.1
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.1
                  tools: composer:v2
            - name: Validate composer.json and composer.lock
              run: composer validate
            - name: Cache module
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/
                  key: composer-cache
            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist --no-progress --no-suggest
            - name: Lint files
              run: composer run phpcs

    analyse-php:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use php 7.4
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  tools: composer:v2
            - name: Cache module
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/
                  key: composer-cache
            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist --no-progress --no-suggest
            - name: Analyse files
              run: composer run phpstan
