name: Run tests

on: 
  push:
  pull_request:
    branches:
      # Branches from forks have the form 'user:branch-name' so we only run
      # this job on pull_request events for branches that look like fork
      # branches. Without this we would end up running this job twice for non
      # forked PRs, once for the push and then once for opening the PR.
      # Source: https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/10
    - '**:**'

jobs:
    test-php:
        name: Test on php ${{ matrix.php-version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                php-version: ["7.1", "7.2", "7.3", "7.4", "8.0"]
                os: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v1
            - name: Use php ${{ matrix.php-version }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: posix, mbstring
                  coverage: xdebug
            - name: Cache module
              uses: actions/cache@v1.0.3
              with:
                  path: ~/.composer/cache/
                  key: composer-cache
            - name: Install dependencies
              if: ${{ matrix.php-version != '8.0' }}
              run: composer install --no-interaction --prefer-dist --no-progress --no-suggest
            - name: Install dependencies for php 8.0
              if: ${{ matrix.php-version == '8.0' }}
              run: composer install --no-interaction --prefer-dist --no-progress --no-suggest --ignore-platform-reqs
            - name: Run php tests
              run: composer run phpunit
            - name: Send coverage
              uses: codecov/codecov-action@v1

    test-phar:
        name: Run command line tests on the phar
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Run phar tests
              uses: sudo-bot/action-shunit2@latest
              with:
                  cli: "./tests/phar/run-tests.sh"
